openapi: 3.0.0
info:
  title: Prog3 - Review API1
  version: 1.0.0
servers:
  - url: https://prog3_server.com
    description: server for tests
paths:
  /books:
    get:
      summary: Get a list of books
      parameters:
        - name: bookName
          in: query
          description: Filter books by name
          schema:
            type: string
        - name: startDate
          in: query
          description: Start date of release date interval
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          description: End date of release date interval
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Successfuly got the list of books
    post:
      summary: Add a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '201':
          description: Book created
    put:
      summary: Update book information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: Book updated successfully
    delete:
      summary: Delete a book by ID
      responses:
        '200':
          description: Book deleted successfully
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
        bookName:
          type: string
        author:
          type: string
        pageNumbers:
          type: integer
        topic:
          type: string
          enum: [ROMANCE, COMEDY, OTHER]
        releaseDate:
          type: string
          format: date
    Author:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        sex:
          type: string
          enum: [M, F]