openapi: 3.0.0
info:
  title: Prog3 - Review API1
  version: 1.0.0
servers:
  - url: https://prog3_server.com
    description: Mock server for testing
paths:
  /group:
    get:
      summary: Get a list of groups
      parameters:
        - name: groupName
          in: query
          description: Filter group by name
          schema:
            type: string
      responses:
        '200':
          description: Successfuly got the list of groups

    put:
      summary: Update the list of groups
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/group'
      responses:
        '200':
          description: Book updated successfully
  /group/year:
    get : 
      summary : Get a list of groups by year
      parameters : 
      - name: groupeYear
        in: query
        description: Filter group by year
        schema : 
          type: string
      responses: 
        '200' : 
          description: Successfuly got the list of groups
  

  /student:
    get:
      summary: Get a list of students
      parameters:
        - name: authorName
          in: query
          description: Filter authors by name
          schema:
            type: string
      responses:
        '200':
          description: Successfuly got a list of students
    post:
      summary: Add a new author
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/student'
      responses:
        '201':
          description: students added successfuly
    put:
      summary: Update author information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/student'
      responses:
        '200':
          description: students updated successfully
    delete:
      summary: Delete an students by ID
      responses:
        '200':
          description: students deleted successfully

components:
  schemas:
    group:
      type: object
      properties:
        id:
          type: integer
        groupName:
          type: string
        groupYear:
          type: integer
        promotion:
          type: string
          enum : [G,H,J,K]
        studentNb:
          type: integer
        students:
          type: array
          items : 
            $ref: '#/components/schemas/student'
          
    student:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        sex:
          type: string
          enum: [M, F]
        birthDate : 
          type: string
          format : date
        reference :
          type: string
          pattern: "^STD\\d{5}$"
        group : 
          type : string

components:
  schemas:
    Group:
      type: object
      properties:
        id:
          type: string
        groupName:
          type: string
        groupYear:
          type: integer
        promotion:
          type: string
          enum:
            - G
            - H
            - J
            - K
        studentNb:
          type: integer
        students:
          type: array
          items:
            $ref: '#/components/schemas/Student'
    Student:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        sex:
          type: string
          enum:
            - M
            - F
        birthdate:
          type: string
          format: date
        reference:
          type: string
          pattern: "^STD\\d{5}$"
        group:
          type: string
