openapi: 3.0.0
info:
  title: Prog3 - Review API1
  version: 1.0.0
servers:
  - url: https://prog3_server.com
    description: Mock server for testing
paths:
  /group:
    get:
      summary: Get a list of books
      parameters:
        - name: bookName
          in: query
          description: Filter books by name
          schema:
            type: string
        - name: startDate
          in: query
          description: Start date of release date interval
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          description: End date of release date interval
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Successfuly got the list of books
    post:
      summary: Add a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/group'
      responses:
        '201':
          description: Book created
    put:
      summary: Update book information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/group'
      responses:
        '200':
          description: Book updated successfully
    delete:
      summary: Delete a book by ID
      responses:
        '200':
          description: Book deleted successfully

  /authors:
    get:
      summary: Get a list of authors
      parameters:
        - name: authorName
          in: query
          description: Filter authors by name
          schema:
            type: string
      responses:
        '200':
          description: Successfuly got a list of authors
    post:
      summary: Add a new author
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        '201':
          description: Author added successfuly
    put:
      summary: Update author information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        '200':
          description: Author updated successfully
    delete:
      summary: Delete an author by ID
      responses:
        '200':
          description: Author deleted successfully

components:
  schemas:
    group:
      type: object
      properties:
        id:
          type: integer
        groupName:
          type: string
        groupYear:
          type: integer
        promotion:
          type: string
          enum : [G,H,J,K]
        studentNb:
          type: integer
        students:
          type: array
          items : student
          
    Author:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        sex:
          type: string
          enum: [M, F]