openapi: 3.0.3
info:
  title: TD1_update
  version: 1.0.0
  description: Mock server for tests

servers:
  - url: https://td1_update.com
paths:
  /groups:
    get:
      summary: Get a list of groups
      parameters:
        - name: groupName
          in: query
          description: Filter groups by name
          schema:
            type: string
        - name: groupYearStart
          in: query
          description: Start of the year
          schema:
            type: integer
        - name: groupYearEnd
          in: query
          description: End of the year
          schema:
            type: integer
      responses:
        '200':
          description: List of groups
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
    post:
      summary: Create a new group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
      responses:
        '200':
          description: Group created
    put:
      summary: Update an existing group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
      responses:
        '200':
          description: Group updated
    delete:
      summary: Delete a group
      parameters:
        - name: groupId
          in: query
          description: ID of the group to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Group deleted
  /students:
    get:
      summary: Get a list of students
      parameters:
        - name: studentName
          in: query
          description: Filter students by name
          schema:
            type: string
      responses:
        '200':
          description: List of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
components:
  schemas:
    Group:
      type: object
      properties:
        id:
          type: string
        groupName:
          type: string
        groupYear:
          type: integer
        promotion:
          type: string
          enum:
            - G
            - H
            - J
            - K
        studentNb:
          type: integer
        students:
          type: array
          items:
            $ref: '#/components/schemas/Student'

    Student:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        sex:
          type: string
          enum:
            - M
            - F
        birthdate:
          type: string
          format: date
        reference:
          type: string
          pattern: "^STD\\d{5}$"
        group:
          type: string
